In [1]:
import pandas as pd
import pylab as pl
import numpy as np
import scipy.optimize as opt
from sklearn import preprocessing
from sklearn.model_selection import train_test_split
%matplotlib inline 
import matplotlib.pyplot as plt

In [2]:
#Import dataset
AccidentData_SVM = pd.read_csv('E:\Training Development\Coursera\IBM Data Science\Course 9 - Capstone Project\Capstone Project Data\AccidentData_4.csv')

In [3]:
AccidentData_SVM.head()

OBJECTID  SEVERITYCODE  JUNCTIONTYPE  WEATHER  ROADCOND  LIGHTCOND  \
0         1             2             2        1         9          6   
1         2             1             3        2         9          3   
2         3             1             3        1         1          6   
3         4             1             3        3         1          6   
4         5             2             2        2         9          6   

   Day of week  Month of Year  
0            2              3  
1            2             12  
2            3             11  
3            4              3  
4            2              1

In [4]:
AccidentData_SVM.dtypes

OBJECTID         int64
SEVERITYCODE     int64
JUNCTIONTYPE     int64
WEATHER          int64
ROADCOND         int64
LIGHTCOND        int64
Day of week      int64
Month of Year    int64
dtype: object

In [5]:
len(AccidentData_SVM.index)

189337

In [6]:
# Define feature set, X
AccidentData_SVM.columns

Index(['OBJECTID', 'SEVERITYCODE', 'JUNCTIONTYPE', 'WEATHER', 'ROADCOND',
       'LIGHTCOND', 'Day of week', 'Month of Year'],
      dtype='object')

In [7]:
feature_df = AccidentData_SVM[['JUNCTIONTYPE', 'WEATHER', 'ROADCOND', 'LIGHTCOND', 'Day of week', 'Month of Year']]
X = np.asarray(feature_df)
X[0:5]

array([[ 2,  1,  9,  6,  2,  3],
       [ 3,  2,  9,  3,  2, 12],
       [ 3,  1,  1,  6,  3, 11],
       [ 3,  3,  1,  6,  4,  3],
       [ 2,  2,  9,  6,  2,  1]], dtype=int64)

In [8]:
# Define the labels
AccidentData_SVM['SEVERITYCODE'] = AccidentData_SVM['SEVERITYCODE'].astype('int')
y = np.asarray(AccidentData_SVM['SEVERITYCODE'])
y [0:5]

array([2, 1, 1, 1, 2])

In [9]:
# Normalise the data
X = preprocessing.StandardScaler().fit(X).transform(X.astype(float))
X[0:10]

array([[-0.97301587, -0.90075769,  1.4789272 ,  0.35007251, -0.49066799,
        -1.04183148],
       [ 0.31901365, -0.49594889,  1.4789272 , -1.40094051, -0.49066799,
         1.58661409],
       [ 0.31901365, -0.90075769, -0.71204349,  0.35007251,  0.02941915,
         1.29456458],
       [ 0.31901365, -0.09114008, -0.71204349,  0.35007251,  0.54950629,
        -1.04183148],
       [-0.97301587, -0.49594889,  1.4789272 ,  0.35007251, -0.49066799,
        -1.62593049],
       [-0.97301587, -0.09114008, -0.71204349,  0.35007251,  1.06959343,
        -0.74978197],
       [-0.97301587, -0.49594889,  1.4789272 ,  0.35007251, -1.01075513,
         1.58661409],
       [-0.97301587, -0.09114008, -0.71204349,  0.35007251, -0.49066799,
        -0.74978197],
       [ 0.31901365, -0.09114008, -0.71204349,  0.35007251,  0.02941915,
        -0.16568296],
       [-0.97301587, -0.09114008, -0.71204349,  0.35007251, -1.53084227,
        -1.04183148]])

In [10]:
# Train / test split
from sklearn.model_selection import train_test_split

In [11]:
X_train, X_test, y_train, y_test = train_test_split( X, y, test_size=0.2, random_state=4)
print ('Train set:', X_train.shape,  y_train.shape)
print ('Test set:', X_test.shape,  y_test.shape)

Train set: (151469, 6) (151469,)
Test set: (37868, 6) (37868,)


In [12]:
# Train the model
from sklearn import svm
clf = svm.SVC(kernel='rbf')
clf.fit(X_train, y_train) 

SVC()

In [13]:
# After being fitted, the model can then be used to predict new values
yhat = clf.predict(X_test)
yhat [0:5]

array([1, 1, 1, 1, 1])

In [ ]:
# EVALUATION

In [14]:
# Measure accuracy
from sklearn.metrics import classification_report, confusion_matrix
import itertools

In [15]:
# Measure accuracy
from sklearn import metrics
print("Train set Accuracy: ", metrics.accuracy_score(y_train, clf.predict(X_train)))
print("Test set Accuracy: ", metrics.accuracy_score(y_test, yhat))

Train set Accuracy:  0.6993048082445913
Test set Accuracy:  0.6961550649625013


In [ ]:
# But, data is not balanced, therefore use the following:
# - F1 score
# - Jaccard index
# - Precision / Recall score

In [25]:
from sklearn.metrics import f1_score
f1_score(y_test, yhat, average='weighted') 

0.5714476046252985

In [28]:
from sklearn.metrics import jaccard_score
jaccard_score(y_test, yhat)

0.6961550649625013

In [29]:
from sklearn.metrics import average_precision_score
average_precision = average_precision_score(y_test, yhat)

print('Average precision-recall score: {0:0.2f}'.format(
      average_precision))

Average precision-recall score: 0.70
