In [1]:
import pandas as pd
import pylab as pl
import numpy as np
import scipy.optimize as opt
from sklearn import preprocessing
%matplotlib inline 
import matplotlib.pyplot as plt

# Import and assess the data set

In [2]:
AccidentData_LogLoss = pd.read_csv('E:\Training Development\Coursera\IBM Data Science\Course 9 - Capstone Project\Capstone Project Data\AccidentData_4.csv')

In [3]:
AccidentData_LogLoss.head()

OBJECTID  SEVERITYCODE  JUNCTIONTYPE  WEATHER  ROADCOND  LIGHTCOND  \
0         1             2             2        1         9          6   
1         2             1             3        2         9          3   
2         3             1             3        1         1          6   
3         4             1             3        3         1          6   
4         5             2             2        2         9          6   

   Day of week  Month of Year  
0            2              3  
1            2             12  
2            3             11  
3            4              3  
4            2              1

In [4]:
len(AccidentData_LogLoss.index)

189337

# Select features X

In [5]:
AccidentData_LogLoss.columns

Index(['OBJECTID', 'SEVERITYCODE', 'JUNCTIONTYPE', 'WEATHER', 'ROADCOND',
       'LIGHTCOND', 'Day of week', 'Month of Year'],
      dtype='object')

# Convert dataset to a numpy array

In [6]:
X = np.asarray(AccidentData_LogLoss[['JUNCTIONTYPE', 'WEATHER', 'ROADCOND', 'LIGHTCOND', 'Day of week', 'Month of Year']])
X[0:5]

array([[ 2,  1,  9,  6,  2,  3],
       [ 3,  2,  9,  3,  2, 12],
       [ 3,  1,  1,  6,  3, 11],
       [ 3,  3,  1,  6,  4,  3],
       [ 2,  2,  9,  6,  2,  1]], dtype=int64)

# Select labels

In [7]:
y = np.asarray(AccidentData_LogLoss['SEVERITYCODE'])
y [0:5]

array([2, 1, 1, 1, 2], dtype=int64)

# Normalize the dataset

In [8]:
from sklearn import preprocessing
X = preprocessing.StandardScaler().fit(X).transform(X)
X[0:5]

array([[-0.97301587, -0.90075769,  1.4789272 ,  0.35007251, -0.49066799,
        -1.04183148],
       [ 0.31901365, -0.49594889,  1.4789272 , -1.40094051, -0.49066799,
         1.58661409],
       [ 0.31901365, -0.90075769, -0.71204349,  0.35007251,  0.02941915,
         1.29456458],
       [ 0.31901365, -0.09114008, -0.71204349,  0.35007251,  0.54950629,
        -1.04183148],
       [-0.97301587, -0.49594889,  1.4789272 ,  0.35007251, -0.49066799,
        -1.62593049]])

# Train/Test split

In [9]:
from sklearn.model_selection import train_test_split
X_train, X_test, y_train, y_test = train_test_split( X, y, test_size=0.2, random_state=4)
print ('Train set:', X_train.shape,  y_train.shape)
print ('Test set:', X_test.shape,  y_test.shape)

Train set: (151469, 6) (151469,)
Test set: (37868, 6) (37868,)


# Create the model and train

In [10]:
from sklearn.linear_model import LogisticRegression
from sklearn.metrics import confusion_matrix
LR = LogisticRegression(C=0.01, solver='liblinear').fit(X_train,y_train)
LR

LogisticRegression(C=0.01, solver='liblinear')

# Predict using the test set

In [11]:
yhat = LR.predict(X_test)
yhat

array([1, 1, 1, ..., 1, 1, 1], dtype=int64)

## Predict_proba returns estimates for all classes, ordered by the label of classes. So, the first column is the probability of class 1, P(Y=1|X), and second column is probability of class 0, P(Y=0|X)

In [12]:
yhat_prob = LR.predict_proba(X_test)
yhat_prob

array([[0.72794576, 0.27205424],
       [0.91862133, 0.08137867],
       [0.73439319, 0.26560681],
       ...,
       [0.703059  , 0.296941  ],
       [0.74152503, 0.25847497],
       [0.59295419, 0.40704581]])

# Evaluate

In [13]:
from sklearn.metrics import classification_report, confusion_matrix
import itertools

In [15]:
from sklearn import metrics
print("Train set Accuracy: ", metrics.accuracy_score(y_train, LR.predict(X_train)))
print("Test set Accuracy: ", metrics.accuracy_score(y_test, yhat))

Train set Accuracy:  0.6957859363962263
Test set Accuracy:  0.6942801309813035


In [ ]:
# But, data is not balanced, therefore use the following:
# - F1 score
# - Jaccard index
# - Precision / Recall score

In [19]:
from sklearn.metrics import f1_score
f1_score(y_test, yhat, average='weighted') 

0.5779906998616631

In [20]:
from sklearn.metrics import jaccard_score
jaccard_score(y_test, yhat)

0.6929992044550517

In [22]:
from sklearn.metrics import average_precision_score
average_precision = average_precision_score(y_test, yhat)

print('Average precision-recall score: {0:0.2f}'.format(
      average_precision))

Average precision-recall score: 0.70


In [16]:
from sklearn.metrics import log_loss
log_loss(y_test, yhat_prob)

0.5832384075902182